public class Example {
    
    public static void changeValue(Integer num) {
        System.debug('befor num'+num);
        num = 100;
        System.debug('after num'+num);
    }

    public static void run() {
        Integer x = 10;
        changeValue(x);
        System.debug(x); 
    }
   
    public static void method5(List<integer>mklist){
        mklist.add(20);
        mklist.add(2);
        mklist.add(20);
        System.debug('mklist'+mklist.size());
        System.debug('Succesfully completed  marklist');
    }
     public static void method6(List<integer>mklist){
        mklist.add(20);
        mklist.add(2);
        mklist.add(20);
        System.debug('mklist'+mklist.size());
        System.debug('Succesfully completed  marklist');
    }
    public static void method7(List<integer>mklist){
        mklist.add(20);
        mklist.add(2);
        mklist.add(20);
        System.debug('mklist'+mklist.size());
        System.debug('Succesfully completed  marklist');
    }
    public static void method8(List<integer>mklist){
        mklist.add(20);
        mklist.add(2);
        mklist.add(20);
        System.debug('mklist'+mklist.size());
        System.debug('Succesfully completed  marklist');
    }
}