name: UpdatedWorkflow
run-name: SFDX Lint with GitHub Actions

on:
  workflow_dispatch:
    inputs:
      OrgName:
        description: 'The name of the Salesforce organization - OpsbridgeDeployClass'
        required: true
      WorkItemTask:
        description: 'The work item task Id to pass Workflow Run Id'
        required: true
      Overall:
        description: 'Run PMD on whole branch (true) or only changed files (false)'
        required: true
        default: 'false'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine Target Files
        id: changes
        run: |
          if [ "${{ github.event.inputs.Overall }}" = "true" ]; then
            echo "Running PMD on entire branch"
            TARGET_FILES=$(find force-app -type f -name "*.cls")
          else
            echo "Running PMD on changed files"
            git fetch origin main --depth=1
            TARGET_FILES=$(git diff --name-only origin/main HEAD \
              | grep '^force-app/.*\.cls$' || true)
          fi

          echo "Files to scan:"
          echo "$TARGET_FILES"

          {
            echo "files<<EOF"
            echo "$TARGET_FILES"
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Setup Java (required for PMD)
        if: steps.changes.outputs.files != ''
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Salesforce CLI
        if: steps.changes.outputs.files != ''
        run: npm install --global @salesforce/cli

      - name: Install Salesforce Scanner Plugin
        if: steps.changes.outputs.files != ''
        run: sf plugins install @salesforce/sfdx-scanner

      - name: Run Salesforce Code Analyzer (Scanner)
        if: steps.changes.outputs.files != ''
        run: |
          mkdir -p reports
          sf scanner:run \
            --format json \
            --target "${{ steps.changes.outputs.files }}" \
            --category "Design,Best Practices,Performance" \
            --outfile reports/scanner-report.json || true

      - name: Upload Salesforce Scanner Report
        if: steps.changes.outputs.files != ''
        uses: actions/upload-artifact@v4
        with:
          name: scanner-report
          path: reports/scanner-report.json

      - name: Run PMD Analysis
        if: steps.changes.outputs.files != ''
        run: |
          mkdir -p reports
          curl -L -o pmd-bin.zip https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.55.0/pmd-bin-6.55.0.zip
          unzip -q pmd-bin.zip
          ./pmd-bin-6.55.0/bin/run.sh pmd \
            -d "${{ steps.changes.outputs.files }}" \
            -R pmd-apex-rules.xml \
            -f json \
            -r reports/pmd-report.json || true

      - name: Upload PMD Report JSON
        if: steps.changes.outputs.files != ''
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: reports/pmd-report.json

      - name: Skip Analysis
        if: steps.changes.outputs.files == ''
        run: echo "No Apex class changes detected. Skipping analysis."
