name: Validate Production Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - 'force-app/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Changed Apex Classes
        id: changes
        run: |
          # Get changed files in PR
          git fetch origin ${{ github.base_ref }} --depth=1
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} HEAD \
            | grep '^force-app/.*\.cls$' || true)
          
          echo "Changed files:"
          echo "$CHANGED_FILES"
          
          # Save for later steps
          {
            echo "files<<EOF"
            echo "$CHANGED_FILES"
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Setup Java (required for PMD)
        if: steps.changes.outputs.files != ''
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Salesforce CLI
        if: steps.changes.outputs.files != ''
        run: npm install --global @salesforce/cli

      - name: Install Salesforce Scanner Plugin
        if: steps.changes.outputs.files != ''
        run: sf plugins install @salesforce/sfdx-scanner

      - name: Run Salesforce Code Analyzer (Scanner) on Changed Files
        if: steps.changes.outputs.files != ''
        run: |
          mkdir -p reports
          sf scanner:run \
            --format json \
            --target "${{ steps.changes.outputs.files }}" \
            --category "Design,Best Practices,Performance" \
            --outfile reports/scanner-report.json || true

      - name: Upload Salesforce Scanner Report
        if: steps.changes.outputs.files != ''
        uses: actions/upload-artifact@v4
        with:
          name: scanner-report
          path: reports/scanner-report.json

      - name: Run PMD Analysis on Changed Files
        if: steps.changes.outputs.files != ''
        run: |
          mkdir -p reports
          curl -L -o pmd-bin.zip https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.55.0/pmd-bin-6.55.0.zip
          unzip -q pmd-bin.zip
          ./pmd-bin-6.55.0/bin/run.sh pmd \
            -d "${{ steps.changes.outputs.files }}" \
            -R force-app/main/default/classes/apex-ruleset.xml \
            -f json \
            -r reports/pmd-report.json || true

      - name: Upload PMD Report JSON
        if: steps.changes.outputs.files != ''
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: reports/pmd-report.json

      - name: Skip Analysis (No Apex Changes)
        if: steps.changes.outputs.files == ''
        run: echo "No Apex class changes detected. Skipping SCA & PMD."
