name: Validate Production Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - 'force-app/**'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate on our Org
        uses: jawills/sf-deploy@v1.0
        with:
          SFDX_AUTH_URL: force://PlatformCLI::5Aep861njAMw_1t53uBO1we.9OJpvHW8T0aRMJpVfv2dqoxgYPNosfFO5VMaGbFGjqgCJB2jj6YqdWtAuJSD5Ld@zyroneenergy-dev-ed.develop.my.salesforce.com
          DRY_RUN: true